---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ducdat2411/python-backend-app:~v0.1.0
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/datdd93/devops-demo.git
    targetRevision: main
    path: backend-config/helm/python-backend-app
    helm:
      parameters:
        - name: "replicaCount"
          value: "1"
        - name: "image.repository"
          value: ducdat2411/python-backend-app
        - name: "image.tag"
          value: "v0.1.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true