---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/datdd93/devops-demo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"