version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - .:/workspace
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.kube/config:/root/.kube/config:ro
    working_dir: /workspace
    entrypoint: /bin/sh
    environment:
      - AWS_PROFILE=default